name: pkgcheck

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pkgcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pkgcore
          key: pkgcheck-${{ hashFiles('**/Manifest') }}
          restore-keys: pkgcheck-

      - name: Run pkgcheck
        uses: pkgcore/pkgcheck-action@v1
        with:
          args: --net
